set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @plugin 'jimeh/tmuxifier'

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -g mouse on

set -g @minimal-tmux-use-arrow true
set -g @minimal-tmux-right-arrow ""
set -g @minimal-tmux-left-arrow ""

run '~/.config/tmux/plugins/tpm/tpm'
